main:
#TOP LEVEL
  - name: Rampe de Lancement
    pageRef: /
    weight: 1
    identifier: home

#TOP LEVEL
  - name: Services
    identifier: services
    weight: 2
  # LEVEL 1
  - name: Experimentation
    parent: services
    pageRef: /services/experimentation
    weight: 1
  - name: Calcul sur demande
    parent: services
    pageRef: /services/calcul-sur-demande
    weight: 2

#TOP LEVEL
  - name: A Propos
    identifier: about
    weight: 3
  # LEVEL 1
  - name: A Propos
    parent: about
    pageRef: /a-propos
    weight: 1
  - name: Glossaire
    parent: about
    pageRef: /glossaire
    weight: 2
  - name: Termes & Conditions
    parent: about
    pageRef: /termes-conditions
    weight: 3
  - name: Politiques
    parent: about
    pageRef: /politiques
    weight: 4
  - name: Contactez Nous
    parent: about
    pageRef: /contactez-nous
    weight: 5

#TOP LEVEL
  - name: Tutoriels
    identifier: tutorials
    pageRef: /tutoriels
    weight: 4
