main:
#TOP LEVEL
  - name: LaunchPad
    pageRef: /
    weight: 1
    identifier: home

#TOP LEVEL
  - name: Services
    identifier: services
    weight: 2
  # LEVEL 1
  - name: Experimentation
    parent: services
    pageRef: /services/experimentation
    weight: 1
  - name: On-Demand Compute
    parent: services
    pageRef: /services/ondemand-compute
    weight: 2


#TOP LEVEL
  - name: About
    identifier: about
    weight: 3
  # LEVEL 1
  - name: About Us
    parent: about
    pageRef: /about-us
    weight: 1
  - name: Glossary
    parent: about
    pageRef: /glossary
    weight: 2
  - name: Terms & Conditions
    parent: about
    pageRef: /terms-conditions
    weight: 3
  - name: Policies
    parent: about
    pageRef: /policies
    weight: 4
  - name: Contact Us
    parent: about
    pageRef: /contact-us
    weight: 5

#TOP LEVEL
  - name: Tutorials
    identifier: tutorials
    pageRef: /tutorials
    weight: 4

private:
#TOP LEVEL
  - name: Private Pages
    pageRef: /private
    weight: 1
    identifier: private
    # LEVEL 1
  - name: Tutorials
    parent: private
    pageRef: /tutorials
    weight: 1
  - name: Foobar
    parent: private
    pageRef: /private/foobar
    weight: 2