main:
#TOP LEVEL
  - name: LaunchPad
    pageRef: /
    weight: 1
    identifier: home


#TOP LEVEL
  - name: About
    identifier: about
    weight: 2
  # LEVEL 1
  - name: About Us
    parent: about
    pageRef: /about-us
    weight: 1

  - name: Terms & Conditions
    parent: about
    pageRef: /terms-conditions
    weight: 2

  - name: Contact Us
    parent: about
    pageRef: /contact-us
    weight: 3


#TOP LEVEL
  - weight: 3
    name: Tutorials
    identifier: tutorials
    pageRef: /tutorials
