main:
#TOP LEVEL
  - name: Rampe de Lancement
    pageRef: /
    weight: 1
    identifier: home


#TOP LEVEL
  - name: A Propos
    identifier: about
    weight: 2
  # LEVEL 1
  - name: A Propos
    parent: about
    pageRef: /a-propos
    weight: 1

  - name: Termes & Conditions
    parent: about
    pageRef: /termes-conditions
    weight: 2
  
  - name: Politiques
    parent: about
    pageRef: /politiques
    weight: 3

  - name: Contactez Nous
    parent: about
    pageRef: /contactez-nous
    weight: 4


#TOP LEVEL
  - weight: 3
    name: Tutoriels
    identifier: tutorials
    pageRef: /tutoriels
